config/routes.rb
Walrus::Application.routes.draw do
  get "test/index"

  resources :answers

  resources :questions

  resources :contacts

  resources :users

  match 'api/v1/test_call' => 'test#test_call'

  match 'api/v1/test_callback' => 'test#test_callback'

  match 'api/v1/test_answer' => 'test#test_answer'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :data, :utccalltime
  belongs_to :user
  belongs_to :contact
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :utccalltime %><br />
    <%= f.datetime_select :utccalltime %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Utccalltime</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.utccalltime %></td>
    <td><%= answer.data %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Utccalltime:</b>
  <%= @answer.utccalltime %>
</p>

<p>
  <b>Data:</b>
  <%= @answer.data %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>